#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Hello World!\n" > /home/ubuntu/hello.html
echo 'server {
    listen 80;

    location / {
        root /home/ubuntu;
        index hello.html;
    }
}' > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
