#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "Hello World!
" > /home/ubuntu/hello.html
# starting nginx service
sudo service nginx start
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
echo 'server {
    listen 80;

    location / {
        root /home/ubuntu;
        index hello.html;
    }
}' > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
