#!/usr/bin/env bash
# Install nginx web server
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        root /home/ubuntu;
        index hello.html;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
