#!/usr/bin/env bash
# Install nginx web server
echo "Hello World!" > /home/ubuntu/hello.html
echo "Ceci n'est pas une page" > /home/ubuntu/404.html
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
    location = /404.html {
        root /home/ubuntu;
    }

}' > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
