#!/usr/bin/env bash
# Install nginx web server
echo "Hello World!" > /home/ubuntu/hello.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
}' > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
