#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get install -y nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /{
      add_header X-Served-By $hostname;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
