#!/usr/bin/env bash
# Install nginx web server
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get update
apt-get install -y -o Dpkg::Options::="--force-confdef" haproxy=2.9.\*
echo 'ENABLED=1' >>  /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
echo '
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 18.207.142.187:80 check
   server web-02 54.152.104.50:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart
