#!/usr/bin/env bash
# Install nginx web server
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get update
apt-get install -y -o Dpkg::Options::="--force-confdef" haproxy=2.9.\*
echo 'ENABLE=1' >>  /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
echo '
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 5000
    timeout client  30000
    timeout server  30000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
   timeout client 30000
   bind 0:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 18.207.142.187:80 check
   server web-02 54.152.104.50:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart
