#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
# sudo apt-get install -y nginx
# sudo sh -c 'echo "
# server {
#     listen 80 default_server;
#     listen [::]:80 default_server;
#     root /var/www/html;
#     index index.html index.htm index.nginx-debian.html;

#     server_name _;
#     location / {
#         try_files \$uri \$uri/ =404;
#     }
# }" > /etc/nginx/default.conf'
cd /etc/nginx/sites-enabled/ || exit;
sudo rm default;
ln -s /etc/nginx/sites-available/default default;
sudo nginx -t
sudo service nginx restart
