#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
cd /etc/nginx/sites-enabled/ || exit
ln -sf /etc/nginx/sites-available/default default
sudo service nginx restart
