#!/usr/bin/env bash
# This Script explains PID
trap '
echo "I hate the kill command" && rm "/var/run/myscript.pid" && pkill -9 -f "100-process_and_pid_file"
' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'pkill -9 -f "100-process_and_pid_file"' SIGQUIT
echo "$$" > "/var/run/myscript.pid"
while true
do
	echo "To infinity and beyond"
	sleep 2
done
