#!/usr/bin/env bash
# This Script explains PID
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [[ -z $process_pid ]]; then
    echo "Process not found."
else
    # Stop the process
    kill $process_pid
    echo "Process stopped successfully."
fi
