#!/usr/bin/env bash
# This Script is to show how for loops work


filename="/etc/passwd"
while IFS=':' read -r USER_NAME USER_PASS USER_ID USER_HOME ignored 
do
echo "$USER_NAME:$USER_ID:$USER_HOME"
done < $filename