#!/usr/bin/env bash
# This Script is to show how while loops work

i=1

until [ $i -eq 10 ]; do
	# ← place the command that returns a non-zero exit code here &>/dev/null
	echo "Best School"
	((i++))
done
